name = "mhsj-read-uv"
main = "src/index.ts"
compatibility_date = "2026-05-22"

routes = [
  { pattern = "mhsj.me/api/views*", zone_name = "mhsj.me" }
]

[[d1_databases]]
binding = "READ_UV_DB"
database_name = "read_uv"
database_id = "8e2644c5-cc67-47da-af7d-c464a529b6fe"

[vars]
ALLOWED_HOST = "mhsj.me"
